interval = 300
profiles=["compliance://admin@example.com/linux-baseline", "compliance://admin@example.com/linux-patch-baseline"]

[reporter]
stdout = false
url = "https://automate.scottford.io/data-collector/v0"
token = "palXrlm3jsFje5ZfMn-0EsXBals="
verify_ssl = true

[compliance]
server = "https://automate.scottford.io"
token = "palXrlm3jsFje5ZfMn-0EsXBals="
user = "admin@example.com"
insecure = false
ent = "default"